import { Router } from 'express';
import { db } from '../db/index.js';

// ─── Print Jobs ───────────────────────────────────────────────────────────────
// An async "AI print" pipeline: queue a task, track its progress via steps.

const router = Router();

// LIST
router.get('/api/projects/:projectId/print-jobs', (req, res) => {
  try {
    const { status, limit = '20' } = req.query as { status?: string; limit?: string };
    let sql    = 'SELECT * FROM print_jobs WHERE project_id = ?';
    const params: unknown[] = [req.params.projectId];

    if (status) { sql += ' AND status = ?'; params.push(status); }
    sql += ' ORDER BY created_at DESC LIMIT ?';
    params.push(parseInt(limit, 10));

    res.json(db.prepare(sql).all(...params));
  } catch (err: unknown) {
    res.status(500).json({ error: (err as Error).message });
  }
});

// CREATE
router.post('/api/projects/:projectId/print-jobs', (req, res) => {
  try {
    const { prompt, model } = req.body as { prompt: string; model?: string };
    if (!prompt) { res.status(400).json({ error: 'prompt required' }); return; }

    const project = db.prepare('SELECT id FROM projects WHERE id = ?').get(req.params.projectId);
    if (!project) { res.status(404).json({ error: 'Project not found' }); return; }

    const job = db.prepare(
      `INSERT INTO print_jobs (project_id, prompt, model) VALUES (?, ?, ?) RETURNING *`,
    ).get(req.params.projectId, prompt, model ?? null) as { id: string };

    res.status(201).json(job);

    // Simulate async pipeline progression
    const steps = [
      { type: 'think', description: `Analyzing: "${prompt.slice(0, 60)}${prompt.length > 60 ? '…' : ''}"`, file_path: null, content: null, result: null },
      { type: 'read',  description: 'Reading project file structure',                                         file_path: null, content: null, result: null },
      { type: 'write', description: 'Creating initial implementation',                                        file_path: 'src/main.ts', content: `// Generated by GateAI\n// Task: ${prompt}\n`, result: null },
      { type: 'run',   description: 'Verifying output',                                                       file_path: null, content: null, result: 'OK' },
    ];

    void (async () => {
      await sleep(500);
      db.prepare(`UPDATE print_jobs SET status = 'printing', updated_at = datetime('now') WHERE id = ?`).run(job.id);

      for (let i = 0; i < steps.length; i++) {
        await sleep(900);
        const s = steps[i]!;
        db.prepare(
          `INSERT INTO print_steps (job_id, step_index, type, description, file_path, content, result)
           VALUES (?, ?, ?, ?, ?, ?, ?)`,
        ).run(job.id, i, s.type, s.description, s.file_path, s.content, s.result);
      }

      await sleep(400);
      db.prepare(`UPDATE print_jobs SET status = 'done', updated_at = datetime('now') WHERE id = ?`).run(job.id);
    })();
  } catch (err: unknown) {
    res.status(500).json({ error: (err as Error).message });
  }
});

// GET
router.get('/api/projects/:projectId/print-jobs/:jobId', (req, res) => {
  const job = db.prepare(
    'SELECT * FROM print_jobs WHERE id = ? AND project_id = ?',
  ).get(req.params.jobId, req.params.projectId);
  if (!job) { res.status(404).json({ error: 'Job not found' }); return; }
  res.json(job);
});

// STEPS
router.get('/api/projects/:projectId/print-jobs/:jobId/steps', (req, res) => {
  res.json(db.prepare('SELECT * FROM print_steps WHERE job_id = ? ORDER BY step_index').all(req.params.jobId));
});

// CANCEL
router.post('/api/projects/:projectId/print-jobs/:jobId/cancel', (req, res) => {
  const job = db.prepare(
    `UPDATE print_jobs SET status = 'cancelled', updated_at = datetime('now')
     WHERE id = ? AND project_id = ? AND status IN ('queued','printing') RETURNING *`,
  ).get(req.params.jobId, req.params.projectId);
  if (!job) { res.status(404).json({ error: 'Job not found or not cancellable' }); return; }
  res.json(job);
});

// RETRY
router.post('/api/projects/:projectId/print-jobs/:jobId/retry', (req, res) => {
  const job = db.prepare(
    `UPDATE print_jobs SET status = 'queued', updated_at = datetime('now')
     WHERE id = ? AND project_id = ? AND status IN ('cancelled','error') RETURNING *`,
  ).get(req.params.jobId, req.params.projectId) as { id: string } | undefined;
  if (!job) { res.status(404).json({ error: 'Job not found or not retryable' }); return; }
  db.prepare('DELETE FROM print_steps WHERE job_id = ?').run(job.id);
  res.json(job);
});

// ─── Util ──────────────────────────────────────────────────────────────────────

function sleep(ms: number): Promise<void> {
  return new Promise(r => setTimeout(r, ms));
}

export default router;
